Repository AY2223S2-CS2103T-W14-4/tp, pull requests merged in 2023-03, with the labels that each got.

#27 Update project details in config.yml file and AboutUs.md
  docs/AboutUs.md
  docs/_config.yml
Labels: documentation

#41 DateTimeParser to help format interview dates
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AdvanceCommand.java
  src/main/java/seedu/address/logic/parser/AdvanceCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DateTimeParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/InterviewDateTime.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/parser/DateTimeParserTest.java
Labels: enhancement

#50 Enhance advance command
  docs/team/fredericchow00.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AdvanceCommand.java
  src/main/java/seedu/address/logic/commands/RejectCommand.java
  src/main/java/seedu/address/logic/parser/AdvanceCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/InterviewDateTime.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
Labels: enhancement

#49 Refactor tag to note
  config/checkstyle/checkstyle.xml
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/note/Note.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedNote.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/note/NoteTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: enhancement

#51 Add interview command
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/InterviewCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DateTimeParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/InterviewDateTime.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/model/util/SortByInterviewDate.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: enhancement

#54 Fix NullPointerException bug
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
Labels: bug

#55 Improve FindCommand predicate checking
  src/main/java/seedu/address/logic/commands/FindCommand.java
Labels: enhancement

#56 Wrote RejectCommandTest and RejectCommandParserTest
  docs/team/fredericchow00.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RejectCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/InterviewDateTime.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/RejectCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/RejectCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: testing

#59 Create test cases for AdvanceCommand
  src/test/java/seedu/address/logic/commands/AdvanceCommandTest.java
Labels: testing

#61 Create test cases for AdvanceCommandParser
  src/test/java/seedu/address/logic/parser/AdvanceCommandParserTest.java
Labels: testing

#67 Enhance find command
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/NoteContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/PersonCard.java
Labels: enhancement

#77 Edit UserGuide: How to use this user guide
  docs/UserGuide.md
  docs/_sass/minima/admonition.scss
  src/main/java/seedu/address/model/note/Note.java
Labels: documentation

#79 Edit User Guider Section: How to use this User Guide
  docs/UserGuide.md
Labels: documentation

#76 Update UG: Troubleshooting, FAQ, Acknowledgements, and Glossary
  docs/UserGuide.md
Labels: documentation

#82 Edit User Guide: About HMHero, Features
  docs/UserGuide.md
  docs/team/jxleejiaxin.md
Labels: documentation

#84 Enhanced EditCommand and EditCommandTest
  build.gradle
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/DateTimeParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: enhancement

#81 Editing User Guide: Commands
  docs/UserGuide.md
Labels: documentation

#80 Branch v1.3 documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/_ug/QuickStart.md
  docs/images/CommandExample.png
  docs/images/components.png
  docs/images/help_window.png
  docs/img.png
  docs/team/fredericchow00.md
  docs/team/merrickneo.md
  src/main/java/seedu/address/logic/commands/SummaryCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: documentation

#68 Implement RemindCommand
  src/main/java/seedu/address/logic/commands/RemindCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/person/InterviewDateTime.java
  src/test/java/seedu/address/logic/commands/RemindCommandTest.java
Labels: enhancement

#89 Update Logic, Model and Commons sections for DG
  config/checkstyle/checkstyle.xml
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/tracing/LogicSequenceDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ParserClasses.png
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/parser/HMHeroParser.java
  src/main/java/seedu/address/model/HMHero.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/AddressBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AdvanceCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/RejectCommandTest.java
  src/test/java/seedu/address/logic/commands/RemindCommandTest.java
  src/test/java/seedu/address/logic/parser/HMHeroParserTest.java
  src/test/java/seedu/address/model/HMHeroTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/JsonHMHeroStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableHMHeroTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: documentation

#92 Update DG: Appendix
  docs/DeveloperGuide.md
  docs/images/application_stage.png
Labels: documentation

#93 Update DG: Add command
  docs/DeveloperGuide.md
Labels: documentation

#99 Change equality checker for the Person class
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: documentation

#107 Update UG: Add quick reference in Glossary
  docs/UserGuide.md
Labels: documentation

#98 Update DG and gradle settings
  build.gradle
  docs/UserGuide.md
Labels: documentation

#106 Enhance FindCommand and FindCommandParser
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/HMHeroParserTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
Labels: enhancement

#111 Edit GUI
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AdvanceCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/InterviewCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/RejectCommand.java
  src/main/java/seedu/address/logic/commands/RemindCommand.java
  src/main/java/seedu/address/logic/commands/SummaryCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/note/Note.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedNote.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/HMHero.css
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/note/NoteTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: enhancement

#113 Edit DG Test Case
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/CommandExample.png
  docs/images/Ui.png
  docs/images/components.png
  docs/images/help_window.png
  src/main/java/seedu/address/logic/commands/AdvanceCommand.java
  src/main/java/seedu/address/logic/commands/SkillCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/resources/images/address_book_32.png
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
Labels: documentation

#117 Update UG: Fix Bug for hyperlink, include new terminology
  docs/UserGuide.md
  docs/images/CommandExample.png
Labels: documentation

#118 Enhanced EditCommand and AdvanceCommand
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AdvanceCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/person/ApplicationDateTime.java
  src/main/java/seedu/address/model/person/InterviewDateTime.java
  src/test/java/seedu/address/logic/commands/AdvanceCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: enhancement

#114 Update DG: Design, Architecture, UI, Logic
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/StorageClassDiagram.png
  docs/team/dunliang0513.md
Labels: documentation

#121 Dg final changes
  README.md
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/add_command.png
  docs/images/advance_command_applied.png
  docs/images/advance_command_shortlisted.png
  docs/images/delete_command_after.png
  docs/images/delete_command_before.png
  docs/images/edit_command_after.png
  docs/images/edit_command_before.png
  docs/images/find_command.png
  docs/images/help_command.png
  docs/images/interview_command.png
  docs/images/list_command.png
  docs/images/reject_command.png
  docs/images/remind_command.png
  docs/images/summary_command.png
  docs/images/ui.png
  docs/index.md
  docs/team/fredericchow00.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AdvanceCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/AdvanceCommandTest.java
Labels: documentation

#119 Update DG: Add FindSequenceDiagram
  docs/DeveloperGuide.md
  docs/diagrams/FindSequenceDiagram.puml
  docs/images/FindSequenceDiagram.png
  docs/team/jxleejiaxin.md
Labels: documentation
