Repository AY2223S2-CS2103T-W14-4/tp, pull requests merged in 2023-04, with the labels that each got.

#169 Fix Invalid Command Error for FindCommand
  docs/team/bofeng1999.md
  src/main/java/seedu/address/logic/commands/FindCommand.java
Labels: bug

#168 PE-D: Fix typo and numeric names
  src/main/java/seedu/address/logic/commands/RemindCommand.java
  src/main/java/seedu/address/model/person/Name.java
  src/test/java/seedu/address/model/person/NameTest.java
Labels: bug

#170 Update UserGuide on FindCommand and AddCommand
  docs/UserGuide.md
Labels: bug

#172 Edit UI bugs
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/SkillCommandParser.java
  src/main/java/seedu/address/model/note/Note.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
Labels: bug

#167 PE-D: Fix bugs
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AdvanceCommand.java
Labels: bug

#171 Update UG and AddCommand
  bin/main/seedu/address/logic/commands/RemindCommand.class
  bin/main/seedu/address/logic/parser/HMHeroParser.class
  bin/main/seedu/address/logic/parser/SkillCommandParser.class
  bin/test/seedu/address/logic/commands/RemindCommandTest.class
  docs/UserGuide.md
  docs/team/merrickneo.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/RemindCommand.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: enhancement

#174 Edit DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/fredericchow00.md
  src/main/java/seedu/address/model/person/Person.java
Labels: documentation

#173 Implement NoteContainsKeywordsPredicateTest and PhoneContainsKeywordsPredicateTest
  docs/UserGuide.md
  docs/images/advance_command_applied.png
  docs/images/advance_command_shortlisted.png
  docs/images/interview_command.png
  docs/images/remind_command.png
  docs/images/skill_command.png
  docs/team/bofeng1999.md
  src/main/java/seedu/address/logic/commands/SkillCommand.java
  src/test/java/seedu/address/model/person/NoteContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PhoneContainsKeywordsPredicateTest.java
Labels: documentation, testing

#176 Add test cases and adjust title for User/Developer Guide
  bin/main/seedu/address/logic/parser/HMHeroParser.class
  bin/main/seedu/address/model/HMHero.class
  bin/main/seedu/address/storage/HMHeroStorage.class
  bin/main/seedu/address/storage/JsonHMHeroStorage.class
  bin/main/view/HMHero.css
  bin/test/seedu/address/logic/LogicManagerTest$JsonHMHeroIoExceptionThrowingStub.class
  bin/test/seedu/address/logic/commands/SummaryCommandTest.class
  bin/test/seedu/address/model/HMHeroTest$HMHeroStub.class
  bin/test/seedu/address/model/HMHeroTest.class
  bin/test/seedu/address/storage/JsonHMHeroStorageTest.class
  bin/test/seedu/address/storage/JsonSerializableHMHeroTest.class
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/_sass/minima/_base.scss
  docs/images/AdvanceActivityDiagram.png
  docs/team/merrickneo.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/SummaryCommand.java
  src/main/java/seedu/address/model/HMHero.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/person/NameAndPhoneContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/HMHeroStorage.java
  src/main/java/seedu/address/storage/JsonHMHeroStorage.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/storage/JsonSerializableHMHero.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/InterviewCommandTest.java
  src/test/java/seedu/address/model/HMHeroTest.java
  src/test/java/seedu/address/storage/JsonHMHeroStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableHMHeroTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: documentation, testing

#177 Update DG: Edit activity diagram
  docs/DeveloperGuide.md
  docs/diagrams/EditApplicantActivityDiagram.puml
  docs/images/EditApplicantActivityDiagram.png
  docs/images/RejectApplicantActivityDiagram.png
  docs/team/jxleejiaxin.md
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: documentation, testing

#175 Update Test Case: Skill Command and Skill Command Parser
  docs/DeveloperGuide.md
  docs/team/dunliang0513.md
  src/main/java/seedu/address/logic/commands/SkillCommand.java
  src/main/java/seedu/address/model/note/Note.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/SkillCommandTest.java
  src/test/java/seedu/address/logic/parser/SkillCommandParserTest.java
Labels: testing

#183 Update ToC
  docs/UserGuide.md
Labels: documentation

#184 Change Note to Info (Blue boxes)
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#185 Edit Javadoc for entire project and remove unused FindCommandParser test case
  src/main/java/seedu/address/AppParameters.java
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/commons/core/LogsCenter.java
  src/main/java/seedu/address/commons/core/Version.java
  src/main/java/seedu/address/commons/core/index/Index.java
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/InterviewCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/RejectCommand.java
  src/main/java/seedu/address/logic/commands/RemindCommand.java
  src/main/java/seedu/address/logic/commands/SummaryCommand.java
  src/main/java/seedu/address/logic/commands/exceptions/CommandException.java
  src/main/java/seedu/address/logic/parser/DateTimeParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/NamePhoneNumberPredicate.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/Status.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiPart.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: documentation
